### ISSUE TITLE
travis builds

### ISSUE THREAD

**Issue by nikolas** [OverByThere/menuitem#5]
Hi, when you get a chance, could you enable travis builds for this repo? You should be able to go to
https://travis-ci.org/profile/OverByThere and enable them. I tried to do this since you added me to the repo but I wasn't able to access this repo from travis. Thanks.

**Comment by OverByThere** [comment]
Hi @nikolas, this has now been done, hope this is okay, should be around for the next 2/3 hours should you need anything else doing.
