### ISSUE TITLE
Separator Support

### ISSUE THREAD

**Issue by BruceBerry** [OverByThere/menuitem#8]
Have you thought about inserting support for two options `separatorbefore` and `separatorafter` to add separators arond the menu item? I added  support for it with a horrible hack but maybe other users are interested in a cleaner implementation by the author.

**Comment by OverByThere** [comment]
I have a feeling this is now fixed, can you confirm?

**Comment by BruceBerry** [comment]
Yes, the recent pull request is the result of me finally having time to turn that horrible hack into a patch  :-)
